### ISSUE TITLE
Clarification regarding fully-connected attention structure

### ISSUE THREAD

**Issue by vardaan123** [QAQ-v/HetGT#5]
For the fully-connected attention structure, does it mean fully connected between all tokens (both nodes and edge tokens) or just the node-edge tokens as shown in Figure 1?

**Comment by QAQ-v** [comment]
Between all tokens.&nbsp;




&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QAQ-v/HetGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月20日(星期二) 下午3:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[QAQ-v/HetGT] Clarification regarding fully-connected attention structure (Issue #5)





 
For the fully-connected attention structure, does it mean fully connected between all tokens (both nodes and edge tokens) or just the node-edge tokens as shown in Figure 1?

**Comment by vardaan123** [comment]
Thanks for the clarification!
